Mohamed m1 @MMGGYY66
alvaroiporre/Ruby-Capstone pull request #31
Opened 2023-08-07 20:45 UTC by MMGGYY66

## Team member 1  @MMGGYY66
- [Create Book class in book.rb](https://github.com/alvaroiporre/Ruby-Capstone/commit/2da69b190dfddcbebfc046bf747dfc4803c1eb54)
- [Create Label class in label.rb](https://github.com/alvaroiporre/Ruby-Capstone/commit/4933423221e83b2b3716d149214c01fa0ced90f9)
- [Create unit test for the book class](https://github.com/alvaroiporre/Ruby-Capstone/commit/df779d8e40844fa246bb0b7275377fb8bc54c72e)
- [Create unit test for the Label class](https://github.com/alvaroiporre/Ruby-Capstone/commit/501b98fc2e5fd903b8e0e2c60461e7c8233ed23d)

2023-08-07 22:05 UTC, PabloEGonz requested changes
Great work, the tests are passing and everything looks good but I noticed the following things that can be improved.

2023-08-07 22:05 UTC, ezekielgn commented on label.rb
> +    @items << item if @items.include?(item) == false
Here you could use unless instead of checking if condition is false.

2023-08-07 22:05 UTC, PabloEGonz commented on app.rb
> +        puts ''
I think it would be better to use puts instead of print, or you can use \n at the end of print if you want to add extra space.

2023-08-07 23:23 UTC, MMGGYY66 commented on label.rb
> +    @items << item if @items.include?(item) == false
Both of them work well. So if it works well, no need to change it. So I think it is optional.

2023-08-07 23:24 UTC, MMGGYY66 commented on app.rb
> +        puts ''
Also. Both of them work well. So if it works well, no need to change it. So I think it is optional.

2023-08-07 23:24 UTC, MMGGYY66 commented
Done

2023-08-08 01:20 UTC, PabloEGonz commented
Great work, your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
* No linter errors ✔️
* Correct GitFlow ✔️
* Good implementations ✔️
* Optional suggestions

2023-08-08 01:21 UTC, PabloEGonz approved these changes

2023-08-08 02:51 UTC, merged

2023-08-08 08:41 UTC, MMGGYY66 commented
thanks